# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xpUzwMFwMxMxQDmEZBTPTeDK5n-ioUaf
"""

import matplotlib.pyplot as plt
# Steps in the flowchart
steps = [
 "Collection of Dataset",
 "Data Preprocessing",
 "Exploratory Data Analysis",
 "Feature Engineering",
 "Model Building",
 "Evaluation & Visualization",
 "Deployment"
 ]
# Create the bar chart
import matplotlib.pyplot as plt
# Steps in the flowchart
steps = [
 "Collection of Dataset",
 "Data Preprocessing",
 "Exploratory Data Analysis",
 "Feature Engineering",
 "Model Building",
 "Evaluation & Visualization",
 "Deployment"
 ]
# Create the bar chart
plt.figure(figsize=(10, 6))
plt.barh(steps[::-1], [1]*len(steps), color='royalblue') # Reverse to
#show top-down
plt.title("Data Science Flowchart (Bar Representation)")
plt.xlabel("Step Progress")
plt.xticks([]) # Hide x-axis values
# Clean style
for spine in ['top', 'right', 'left']:
    plt.gca().spines[spine].set_visible(False)
plt.tight_layout()
plt.show()
plt.xticks([]) # Hide x-axis values
# Clean style
for spine in ['top', 'right', 'left']:
 plt.gca().spines[spine].set_visible(False)
plt.tight_layout()
plt.show()